
package com.knight.estoque;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ListagemLivros", targetNamespace = "http://servicos.estoque.knight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListagemLivros {


    /**
     * 
     * @return
     *     returns java.util.List<com.knight.estoque.Livro>
     */
    @WebMethod
    @WebResult(name = "livro", targetNamespace = "")
    @RequestWrapper(localName = "listarLivros", targetNamespace = "http://servicos.estoque.knight.com/", className = "com.knight.estoque.ListarLivros")
    @ResponseWrapper(localName = "listarLivrosResponse", targetNamespace = "http://servicos.estoque.knight.com/", className = "com.knight.estoque.ListarLivrosResponse")
    @Action(input = "http://servicos.estoque.knight.com/ListagemLivros/listarLivrosRequest", output = "http://servicos.estoque.knight.com/ListagemLivros/listarLivrosResponse")
    public List<Livro> listarLivros();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<com.knight.estoque.Livro>
     */
    @WebMethod
    @WebResult(name = "livro", targetNamespace = "")
    @RequestWrapper(localName = "listarLivrosPaginacao", targetNamespace = "http://servicos.estoque.knight.com/", className = "com.knight.estoque.ListarLivrosPaginacao")
    @ResponseWrapper(localName = "listarLivrosPaginacaoResponse", targetNamespace = "http://servicos.estoque.knight.com/", className = "com.knight.estoque.ListarLivrosPaginacaoResponse")
    @Action(input = "http://servicos.estoque.knight.com/ListagemLivros/listarLivrosPaginacaoRequest", output = "http://servicos.estoque.knight.com/ListagemLivros/listarLivrosPaginacaoResponse")
    public List<Livro> listarLivrosPaginacao(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

}
