
package com.knight.estoque;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ListagemLivrosService", targetNamespace = "http://servicos.estoque.knight.com/", wsdlLocation = "http://localhost:8080/livros?wsdl")
public class ListagemLivrosService
    extends Service
{

    private static final URL LISTAGEMLIVROSSERVICE_WSDL_LOCATION;
    private static final WebServiceException LISTAGEMLIVROSSERVICE_EXCEPTION;
    private static final QName LISTAGEMLIVROSSERVICE_QNAME = new QName("http://servicos.estoque.knight.com/", "ListagemLivrosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/livros?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAGEMLIVROSSERVICE_WSDL_LOCATION = url;
        LISTAGEMLIVROSSERVICE_EXCEPTION = e;
    }

    public ListagemLivrosService() {
        super(__getWsdlLocation(), LISTAGEMLIVROSSERVICE_QNAME);
    }

    public ListagemLivrosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAGEMLIVROSSERVICE_QNAME, features);
    }

    public ListagemLivrosService(URL wsdlLocation) {
        super(wsdlLocation, LISTAGEMLIVROSSERVICE_QNAME);
    }

    public ListagemLivrosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAGEMLIVROSSERVICE_QNAME, features);
    }

    public ListagemLivrosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListagemLivrosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListagemLivros
     */
    @WebEndpoint(name = "ListagemLivrosPort")
    public ListagemLivros getListagemLivrosPort() {
        return super.getPort(new QName("http://servicos.estoque.knight.com/", "ListagemLivrosPort"), ListagemLivros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListagemLivros
     */
    @WebEndpoint(name = "ListagemLivrosPort")
    public ListagemLivros getListagemLivrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.estoque.knight.com/", "ListagemLivrosPort"), ListagemLivros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAGEMLIVROSSERVICE_EXCEPTION!= null) {
            throw LISTAGEMLIVROSSERVICE_EXCEPTION;
        }
        return LISTAGEMLIVROSSERVICE_WSDL_LOCATION;
    }

}
